### ISSUE TITLE
 InfluxDB-Client-for-Arduino doesn't work on wired Ethernet.

### ISSUE THREAD

**Issue by ykpark1126** [tobiasschuerg/InfluxDB-Client-for-Arduino#189]
__Proposal:__
InfluxDB-Client-for-Arduino works well on Wifi. but it didn't work on wired Ethernet.

__Current behavior:__
I tried to connect InfluxDb on wired Ethernet, but failed. Ethernet chip is W5500.

__Desired behavior:__
I want to connect InfluxDb on wired Ethernet.

__Alternatives considered:__
but, I'm not good enough to do it.

__Use case:__
Wired Ethernet is more reliable.

**Comment by vlastahajek** [comment]
@ykpark1126, thanks for trying this client. Only connection over internal WiFi is supported now. Please follow issue #127 about Ethernet support.

**Comment by nguyenlamlll** [comment]
HI @vlastahajek, I'm sorry to revive this old issue, but I feel my question relates a bit to your answer. What does `internal Wifi` mean, can you please elaborate here? If I have an InfluxDB on a remote server on Azure/AWS, will my board connect successfully? I assume I cannot, because internal means the InfluxDB has to be in the same network...? 
Many thanks.

**Comment by vlastahajek** [comment]
@nguyenlamlll, by `internal WiFi` I meant WiFi capability of ESP chip. Not an external peripheral
