### ISSUE TITLE
Cert changed again

### ISSUE THREAD

**Issue by cail** [tobiasschuerg/InfluxDB-Client-for-Arduino#63]
Sooo.. they changed cert and fingerprint again?

//#define INFLUXDB_FINGER "16 0E 8D FE A4 1C E0 63 FB 75 F5 BB 63 8F 1B E3 3D 93 55 05"
#define INFLUXDB_FINGER "58 04 D0 88 2D 0A 38 D3 E2 A6 A2 F8 42 0E 0C A0 4F CC CF 13"

Have to reflash all my sensor devices ((

Any idea how this could be fixed?

**Comment by vlastahajek** [comment]
@cail, probably due to security reasons, they are changing **server** certificate every 3 months.
So, for establishing a connection to the InfluxDB 2 Cloud server is much better to use [CA certificate](https://github.com/tobiasschuerg/InfluxDB-Client-for-Arduino/blob/master/src/InfluxDbCloud.h#L31) included with the lib, which has a longer validity.

Don't forget to sync time, if you are already not doing that yet.

Note: you cannot use fingerprint of the CA certificate.

**Comment by cail** [comment]
I'm on battery based esp, not very interested in taking NTP stuff. So here's alternative:
https://github.com/tobiasschuerg/InfluxDB-Client-for-Arduino/pull/64

**Comment by vlastahajek** [comment]
Closed via #64
