### ISSUE TITLE
Buffer _flushInterval is not explained

### ISSUE THREAD

**Issue by pickmylight** [tobiasschuerg/InfluxDB-Client-for-Arduino#82]
Thanks in advance for this library! 
It works absolutely perfectly to my needs. 

There is one thing I should mention: You forgot to explain the _flushInterval in checkBuffer(). 

Got me exactly half an hour to figure out, why my 15 minute batch never filled the buffer. It would be a charm, if there is a simple (I know there is with setWriteOptions) and yet documented version of setting the _flushinterval from 60 seconds up.
Just a friendly reminder :)

**Comment by vlastahajek** [comment]
@pickmylight,  [API documentation](https://github.com/tobiasschuerg/InfluxDB-Client-for-Arduino/blob/master/src/InfluxDbClient.h#L187) and [readme](https://github.com/tobiasschuerg/InfluxDB-Client-for-Arduino#buffer-handling-and-retrying) describes `checkBuffer()`:
_Checks points buffer status and flushes if number of points reached batch size or flush interval runs out_.  

You, probably, mean that `writePoint` and `writeRecord` should have an explanation of what happens when batching is applied.

It also seems to me, that flush interval should be bigger, e.g. 10 mins.

**Comment by pickmylight** [comment]
@vlastahajek 
Exactly! That's what I'm talking about. 

The flush interval fits perfectly in highperformance use cases. But with the limited resources and Networkcapability one minute is quite a small time.
